base_url = "https://blog.skyplabs.net"

title = "Skyper's blog"
description = "Personal blog about IT, Electronics, InfoSec, Hacking, Bug Hunting..."

default_language = "en"

compile_sass = true
build_search_index = true
generate_feed = true

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[translations]
next_page = "Next"
previous_page = "Previous"
edit_on_github = "Edit this post on GitHub"
read_more = "Read more"
related_posts = "Latest Posts"
search_bar = "Search for a post, a tag, a category..."
no_search_results = "No results found"

[extra]
author.first_name = "Paul-Emmanuel"
author.last_name = "Raoul"
author.nickname = "Skyper"

github.url = "https://github.com/SkypLabs/personal-blog"
github.branch = "content"

meta.keywords = "Blog, Computer Science, IT, Electronics, Hacking, InfoSec, CTF, Bug Bounty, Open Source"

plausible = ""

settings.date_format_posts = "%d %b %Y"

social.github = "SkypLabs"
social.docker_hub = "skyplabs"
social.twitter = "SkypLabs"
social.linkedin = "peraoul"
social.keybase = "skyplabs"
social.email = "skyper@skyplabs.net"
