name: Test

on:
  - push
  - pull_request

jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/content'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
          CHECK_LINKS: true
